# Generated by Django 5.0.2 on 2025-03-12 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial_data'),
        ('events', '0003_sample_data'),
    ]

    operations = [
    ]
